before_script:
  - export BUILD_PREFIX=buildref${CI_BUILD_REF}$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export COMPOSE_PROJECT_NAME=${BUILD_PREFIX}
  - cd build

stages:
  - lint
  - build
  - cleanup
  - deploy

lint:
  stage: lint
  script:
    - docker-compose run --rm write-good
  allow_failure: true

build:
  stage: build
  script:
    - ls -la
    - pwd
    - docker-compose build
    - docker-compose run --rm builder composer install
    - docker-compose run --rm builder ls -la /app/docs/build
    - docker-compose run --rm builder sh /app/docs/build/generate-docs.sh
  artifacts:
    paths:
      - tmp/apidocs

cleanup:
  stage: cleanup
  script:
    - docker-compose kill && docker-compose rm -fv
    - docker-compose down
  when: always