version: "2"

services:
  write-good:
    build:
      dockerfile: Dockerfile-writegood
      context: ./build
    command: "sh -c 'cd /app && write-good */*.md'"
    volumes:
      - ./:/app

  builder:
    build:
      dockerfile: Dockerfile-docs
      context: ./build
    command: bash
    volumes:
      - ./:/app/docs
      - ./tmp/apidocs:/app/web/apidocs
      - ./tmp/vendor:/app/vendor